use crate::model::{Document, Item, ItemKind, Section, Shortcut};
use std::path::PathBuf;

const DOCTYPE_LINE: &str = "<!DOCTYPE html>";
const HTML_OPEN: &str = "<html lang=\"ja\">";
const HTML_CLOSE: &str = "</html>";
const GENERATED_MARKER: &str = "<!--THIS FILE IS GENERATED BY URLS EDITOR-->";
const DETAILS_OPEN: &str = "<details open>";
const DETAILS_CLOSE: &str = "</details>";
const DETAIL_CONTENT_OPEN: &str = "<div class=\"detail-content\">";
const DETAIL_CONTENT_CLOSE: &str = "</div>";
const SUMMARY_OPEN: &str = "<summary class=\"summary\">";
const SUMMARY_CLOSE: &str = "</summary>";
const TEXT_ITEM_OPEN: &str = "<span>";
const TEXT_ITEM_CLOSE: &str = "</span><br>";
const KEY_VIEWER_OPEN: &str = "<span class=\"key-viewer\">[";
const KEY_VIEWER_FULLOPEN_OPEN: &str = "<span class=\"key-viewer-fullopen\">[";
const KEY_VIEWER_CLOSE: &str = "]</span>";
const KEY_VIEWER_FULLOPEN_NONE_OPEN: &str =
    "<span class=\"key-viewer-fullopen\" data-shortcut=\"none\" data-urls=\"";
const KEY_VIEWER_FULLOPEN_NONE_MID: &str = "\"></span>";
const LINK_OPEN: &str = "<a href=\"";
const LINK_CLOSE: &str = "</a><br>";
const COPY_BUTTON_OPEN: &str = "<button onclick=\"";
const COPY_BUTTON_CLOSE: &str = " <i class=\"fa-regular fa-copy\"></i></button><br>";
const MANUAL_LINE_BREAK: &str = "<!--MANUAL LINE BREAK-->";
const SCRIPT_OPEN: &str = "<script>";
const SCRIPT_CLOSE: &str = "</script>";
const LINK_SHORTCUT_MARKER: &str = "// urls-editor:link";
const MULTI_LINK_SHORTCUT_MARKER: &str = "// urls-editor:multilink";

#[derive(Debug)]
pub enum HtmlError {
    MissingMarker,
    InvalidStructure(String),
    Io(std::io::Error),
}

impl From<std::io::Error> for HtmlError {
    fn from(value: std::io::Error) -> Self {
        Self::Io(value)
    }
}

impl std::fmt::Display for HtmlError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MissingMarker => write!(f, "missing generated HTML marker"),
            Self::InvalidStructure(message) => write!(f, "invalid HTML structure: {message}"),
            Self::Io(error) => write!(f, "I/O error: {error}"),
        }
    }
}

impl std::error::Error for HtmlError {}

pub fn rapid_path() -> PathBuf {
    std::env::current_exe()
        .ok()
        .and_then(|path| path.parent().map(|p| p.to_path_buf()))
        .unwrap_or_else(|| PathBuf::from("."))
        .join("Rapid.html")
}

pub fn load_document_from_path(path: &std::path::Path) -> Result<Document, HtmlError> {
    let content = std::fs::read_to_string(path)?;
    parse_document(&content)
}

pub fn save_document_to_path(document: &Document, path: &std::path::Path) -> Result<(), HtmlError> {
    std::fs::write(path, render_document(document))?;
    Ok(())
}

fn html_text_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn html_attr_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn js_single_quoted_string_escape(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\'', "\\'")
        .replace('"', "\\\"")
}

fn onclick_copy_handler(body: &str) -> String {
    let js = format!("clipping('{}')", js_single_quoted_string_escape(body));
    html_attr_escape(&js)
}

pub fn render_document(document: &Document) -> String {
    let mut out = String::new();
    write_document_header(&mut out);
    let mut shortcuts = String::new();
    let mut detail_id = 0usize;
    for section in &document.sections {
        render_section(section, &mut detail_id, &mut out, &mut shortcuts);
    }
    write_document_controls(&mut out);
    out.push_str(SCRIPT_OPEN);
    out.push('\n');
    write_script_body(&mut out, &shortcuts);
    out.push_str(SCRIPT_CLOSE);
    out.push('\n');
    write_document_footer(&mut out);
    out
}

pub fn parse_document(input: &str) -> Result<Document, HtmlError> {
    if !input.contains(GENERATED_MARKER) {
        return Err(HtmlError::MissingMarker);
    }

    let mut stack: Vec<Section> = Vec::new();
    let mut root_sections = Vec::new();
    let mut in_script = false;
    let mut script_lines = Vec::new();

    for line in input.lines() {
        let trimmed = line.trim();
        if in_script {
            if trimmed == SCRIPT_CLOSE {
                in_script = false;
            } else {
                script_lines.push(trimmed.to_string());
            }
            continue;
        }

        if trimmed == SCRIPT_OPEN {
            in_script = true;
            continue;
        }

        match parse_line(trimmed)? {
            ParsedLine::Ignored => {}
            ParsedLine::OpenSection => stack.push(Section::new("")),
            ParsedLine::SectionTitle(value) => {
                let section = current_section_mut(&mut stack, "summary outside section")?;
                section.title = html_unescape(value);
            }
            ParsedLine::TextItem(value) => {
                let section = current_section_mut(&mut stack, "text item outside section")?;
                section.items.push(Item::text(html_unescape(value)));
            }
            ParsedLine::LinkItem {
                text,
                url,
                shortcut,
            } => {
                let section = current_section_mut(&mut stack, "link item outside section")?;
                section.items.push(Item::link(text, url, shortcut));
            }
            ParsedLine::MultiLinkItem {
                text,
                urls,
                shortcut,
            } => {
                let section = current_section_mut(&mut stack, "multi-link item outside section")?;
                section.items.push(Item::multi_link(text, urls, shortcut));
            }
            ParsedLine::CopyButtonItem { text, body } => {
                let section = current_section_mut(&mut stack, "copy button outside section")?;
                section.items.push(Item::copy_button(text, body));
            }
            ParsedLine::ManualLineBreak => {
                current_section_mut(&mut stack, "manual line break outside section")?
                    .items
                    .push(parsed_line_break_item())
            }
            ParsedLine::CloseSection => close_section(&mut stack, &mut root_sections)?,
        }
    }

    if !stack.is_empty() {
        return Err(invalid_structure("unclosed <details>"));
    }

    if in_script {
        return Err(invalid_structure("unclosed <script>"));
    }

    let shortcut_blocks = parse_script_shortcut_blocks(&script_lines);
    restore_multi_link_urls(&mut root_sections, &shortcut_blocks);

    Ok(Document {
        sections: root_sections,
    })
}

fn render_section(
    section: &Section,
    detail_id: &mut usize,
    out: &mut String,
    shortcuts: &mut String,
) {
    out.push_str(&format!("<details id=\"detail-{}\" open>\n", *detail_id));
    *detail_id += 1;
    out.push_str(&format!(
        "{SUMMARY_OPEN}{}{SUMMARY_CLOSE}\n",
        html_text_escape(&section.title)
    ));
    out.push_str(DETAIL_CONTENT_OPEN);
    out.push('\n');

    for item in &section.items {
        match &item.kind {
            ItemKind::Link {
                text,
                url,
                shortcut,
            } => {
                let key = shortcut_label(*shortcut);
                if let Some(key) = key {
                    out.push_str(&format!("<span class=\"key-viewer\">[{key}]</span>"));
                    push_link_shortcut(shortcuts, *shortcut, url);
                }
                out.push_str(&format!(
                    "<a href=\"{}\" target=\"_blank\" rel=\"noopener noreferrer\">{}</a><br>\n",
                    html_attr_escape(url),
                    html_text_escape(text)
                ));
            }
            ItemKind::MultiLink {
                text,
                urls,
                shortcut,
            } => {
                match shortcut_label(*shortcut) {
                    Some(key) => out.push_str(&format!(
                        "<span class=\"key-viewer-fullopen\">[{key}]</span>{}<br>\n",
                        html_text_escape(text)
                    )),
                    None => out.push_str(&format!(
                        "{KEY_VIEWER_FULLOPEN_NONE_OPEN}{}{KEY_VIEWER_FULLOPEN_NONE_MID}{}<br>\n",
                        multi_link_urls_attr_escape(urls),
                        html_text_escape(text)
                    )),
                }
                push_multi_link_shortcut(shortcuts, *shortcut, urls);
            }
            ItemKind::CopyButton { text, body } => {
                out.push_str(&format!(
                    "<button onclick=\"{}\">{} <i class=\"fa-regular fa-copy\"></i></button><br>\n",
                    onclick_copy_handler(body),
                    html_text_escape(text)
                ));
            }
            ItemKind::Text { text } => {
                out.push_str(&format!(
                    "{TEXT_ITEM_OPEN}{}{TEXT_ITEM_CLOSE}\n",
                    html_text_escape(text)
                ));
            }
            ItemKind::LineBreak => {
                out.push_str(MANUAL_LINE_BREAK);
                out.push('\n');
            }
        }
    }

    for child in &section.sections {
        render_section(child, detail_id, out, shortcuts);
    }

    out.push_str(DETAIL_CONTENT_CLOSE);
    out.push('\n');
    out.push_str(DETAILS_CLOSE);
    out.push_str("\n<br><br>\n");
}

fn shortcut_label(shortcut: Shortcut) -> Option<&'static str> {
    match shortcut {
        Shortcut::None => None,
        Shortcut::Key('A') => Some("A"),
        Shortcut::Key('B') => Some("B"),
        Shortcut::Key('C') => Some("C"),
        Shortcut::Key('D') => Some("D"),
        Shortcut::Key('E') => Some("E"),
        Shortcut::Key('F') => Some("F"),
        Shortcut::Key('G') => Some("G"),
        Shortcut::Key('H') => Some("H"),
        Shortcut::Key('I') => Some("I"),
        Shortcut::Key('J') => Some("J"),
        Shortcut::Key('K') => Some("K"),
        Shortcut::Key('L') => Some("L"),
        Shortcut::Key('M') => Some("M"),
        Shortcut::Key('N') => Some("N"),
        Shortcut::Key('O') => Some("O"),
        Shortcut::Key('P') => Some("P"),
        Shortcut::Key('Q') => Some("Q"),
        Shortcut::Key('R') => Some("R"),
        Shortcut::Key('S') => Some("S"),
        Shortcut::Key('T') => Some("T"),
        Shortcut::Key('U') => Some("U"),
        Shortcut::Key('V') => Some("V"),
        Shortcut::Key('W') => Some("W"),
        Shortcut::Key('X') => Some("X"),
        Shortcut::Key('Y') => Some("Y"),
        Shortcut::Key('Z') => Some("Z"),
        Shortcut::Key(_) => None,
        Shortcut::Alt => Some("Alt"),
        Shortcut::ShiftSpace => Some("Shift + Space"),
    }
}

fn write_script_body(out: &mut String, shortcuts: &str) {
    out.push_str("const animTiming = {\n");
    out.push_str("  duration: 200,\n");
    out.push_str("  easing: \"ease-in-out\",\n");
    out.push_str("};\n");
    out.push_str("const closingAnimation = (content) => [\n");
    out.push_str("  {\n");
    out.push_str("    height: content.offsetHeight + \"px\",\n");
    out.push_str("    opacity: 1,\n");
    out.push_str("  },\n");
    out.push_str("  {\n");
    out.push_str("    height: 0,\n");
    out.push_str("    opacity: 0,\n");
    out.push_str("  },\n");
    out.push_str("];\n");
    out.push_str("const openingAnimation = (content) => [\n");
    out.push_str("  {\n");
    out.push_str("    height: 0,\n");
    out.push_str("    opacity: 0,\n");
    out.push_str("  },\n");
    out.push_str("  {\n");
    out.push_str("    height: content.offsetHeight + \"px\",\n");
    out.push_str("    opacity: 1,\n");
    out.push_str("  },\n");
    out.push_str("];\n");
    out.push_str("document.querySelectorAll('button').forEach((button) => {\n");
    out.push_str("  button.addEventListener('mousedown', function() {\n");
    out.push_str("    this.classList.add('active');\n");
    out.push_str("    setTimeout(() => {\n");
    out.push_str("      this.classList.remove('active');\n");
    out.push_str("    }, 140);\n");
    out.push_str("  });\n");
    out.push_str("});\n");
    out.push_str("const themeButton = document.querySelector('#theme');\n");
    out.push_str("function applyThemeState() {\n");
    out.push_str("  const isDarkTheme = localStorage.getItem('dark-theme');\n");
    out.push_str("  if (isDarkTheme === 'true') {\n");
    out.push_str("    document.body.classList.add('dark-theme');\n");
    out.push_str("    themeButton.innerText = 'light theme';\n");
    out.push_str("  } else {\n");
    out.push_str("    document.body.classList.remove('dark-theme');\n");
    out.push_str("    themeButton.innerText = 'dark theme';\n");
    out.push_str("  }\n");
    out.push_str("}\n");
    out.push_str("themeButton.onclick = function() {\n");
    out.push_str("  document.body.classList.toggle('dark-theme');\n");
    out.push_str("  themeButton.innerText = document.body.classList.contains('dark-theme') ? 'light theme' : 'dark theme';\n");
    out.push_str(
        "  localStorage.setItem('dark-theme', document.body.classList.contains('dark-theme'));\n",
    );
    out.push_str("};\n");
    out.push_str("const memoTab = document.getElementById('memo');\n");
    out.push_str("const memoShell = document.getElementById('memo-shell');\n");
    out.push_str("const memoResizeHandle = document.getElementById('memo-resize-handle');\n");
    out.push_str("const INITIAL_MEMO_WIDTH_RATIO = 0.5;\n");
    out.push_str("const MEMO_MAX_WIDTH_MULTIPLIER = 1.25;\n");
    out.push_str("const MIN_MEMO_LEFT = 470;\n");
    out.push_str("const MIN_MEMO_WIDTH = 288;\n");
    out.push_str("memoTab.addEventListener('input', function() {\n");
    out.push_str("  localStorage.setItem('memo', this.value);\n");
    out.push_str("});\n");
    out.push_str("document.addEventListener('DOMContentLoaded', function() {\n");
    out.push_str("  applyThemeState();\n");
    out.push_str("  const savedText = localStorage.getItem('memo');\n");
    out.push_str("  if (savedText) {\n");
    out.push_str("    memoTab.value = savedText;\n");
    out.push_str("  }\n");
    out.push_str(
        "  memoShell.style.width = `${Math.round(window.innerWidth * INITIAL_MEMO_WIDTH_RATIO)}px`;\n",
    );
    out.push_str("  const allDetails = document.querySelectorAll('details');\n");
    out.push_str("  allDetails.forEach((details) => {\n");
    out.push_str("    const summary = details.querySelector('.summary');\n");
    out.push_str("    const content = details.querySelector('.detail-content');\n");
    out.push_str("    const isOpen = localStorage.getItem(details.id);\n");
    out.push_str("    if (isOpen === 'false') {\n");
    out.push_str("      details.removeAttribute('open');\n");
    out.push_str("    }\n");
    out.push_str("    summary.addEventListener('click', (event) => {\n");
    out.push_str("      event.preventDefault();\n");
    out.push_str("      if (details.getAttribute('open') !== null) {\n");
    out.push_str(
        "        const closingAnim = content.animate(closingAnimation(content), animTiming);\n",
    );
    out.push_str("        closingAnim.onfinish = () => {\n");
    out.push_str("          details.removeAttribute('open');\n");
    out.push_str("        };\n");
    out.push_str("      } else {\n");
    out.push_str("        details.setAttribute('open', 'true');\n");
    out.push_str("        content.animate(openingAnimation(content), animTiming);\n");
    out.push_str("      }\n");
    out.push_str("    });\n");
    out.push_str("    details.addEventListener('toggle', function() {\n");
    out.push_str("      localStorage.setItem(details.id, details.open);\n");
    out.push_str("    });\n");
    out.push_str("  });\n");
    out.push_str("  resizeMemo();\n");
    out.push_str("});\n");
    out.push_str("const tabInsert = function(e) {\n");
    out.push_str("  if (e.key === 'Tab') {\n");
    out.push_str("    e.preventDefault();\n");
    out.push_str("    const start = this.selectionStart;\n");
    out.push_str("    const end = this.selectionEnd;\n");
    out.push_str("    const beforeStart = this.value.substring(0, start);\n");
    out.push_str("    const indexOfStartOfLine = beforeStart.lastIndexOf('\\n') + 1;\n");
    out.push_str("    const selectedTextIncludingWholeLines = this.value.substring(indexOfStartOfLine, end);\n");
    out.push_str("    const lines = selectedTextIncludingWholeLines.split('\\n');\n");
    out.push_str("    if (lines.length >= 2 && start !== end) {\n");
    out.push_str("      let newTextIncludingWholeLines;\n");
    out.push_str("      if (e.shiftKey) {\n");
    out.push_str("        newTextIncludingWholeLines = selectedTextIncludingWholeLines.replace(/^\\t/gm, '');\n");
    out.push_str("        this.selectionStart = start - (selectedTextIncludingWholeLines.split('\\n')[0].startsWith('\\t') ? 1 : 0);\n");
    out.push_str("      } else {\n");
    out.push_str("        newTextIncludingWholeLines = selectedTextIncludingWholeLines.replace(/^/gm, '\\t');\n");
    out.push_str("        this.selectionStart = start + 1;\n");
    out.push_str("      }\n");
    out.push_str("      this.value = this.value.substring(0, indexOfStartOfLine) + newTextIncludingWholeLines + this.value.substring(end);\n");
    out.push_str(
        "      this.selectionEnd = indexOfStartOfLine + newTextIncludingWholeLines.length;\n",
    );
    out.push_str("    } else {\n");
    out.push_str(
        "      this.value = this.value.substring(0, start) + '\\t' + this.value.substring(end);\n",
    );
    out.push_str("      this.selectionStart = start + 1;\n");
    out.push_str("      this.selectionEnd = start + 1;\n");
    out.push_str("    }\n");
    out.push_str("    localStorage.setItem('memo', this.value);\n");
    out.push_str("  }\n");
    out.push_str("  if (e.keyCode === 13) {\n");
    out.push_str("    e.preventDefault();\n");
    out.push_str("    const position = this.selectionStart;\n");
    out.push_str("    const end = this.selectionEnd;\n");
    out.push_str("    const textBefore = this.value.substring(0, position);\n");
    out.push_str("    const textAfter = this.value.substring(end, this.value.length);\n");
    out.push_str(
        "    const prevNewlinePos = this.value.substring(0, position).lastIndexOf('\\n');\n",
    );
    out.push_str("    const leftPartLine = this.value.substring(prevNewlinePos + 1, position);\n");
    out.push_str("    let numOfTabs = 0;\n");
    out.push_str("    for (let i = 0; i < leftPartLine.length; i += 1) {\n");
    out.push_str("      if (leftPartLine[i] === '\\t') {\n");
    out.push_str("        numOfTabs += 1;\n");
    out.push_str("      } else {\n");
    out.push_str("        break;\n");
    out.push_str("      }\n");
    out.push_str("    }\n");
    out.push_str("    const tabs = '\\t'.repeat(numOfTabs);\n");
    out.push_str("    if ((textBefore.endsWith('(') && textAfter.startsWith(')')) || (textBefore.endsWith('[') && textAfter.startsWith(']')) || (textBefore.endsWith('{') && textAfter.startsWith('}'))) {\n");
    out.push_str(
        "      this.value = textBefore + '\\n' + tabs + '\\t' + '\\n' + tabs + textAfter;\n",
    );
    out.push_str("      this.selectionStart = position + 2 + tabs.length;\n");
    out.push_str("      this.selectionEnd = position + 2 + tabs.length;\n");
    out.push_str("    } else {\n");
    out.push_str("      this.value = this.value.substring(0, position) + '\\n' + tabs + this.value.substring(position);\n");
    out.push_str("      this.selectionStart = position + tabs.length + 1;\n");
    out.push_str("      this.selectionEnd = position + tabs.length + 1;\n");
    out.push_str("    }\n");
    out.push_str("    localStorage.setItem('memo', this.value);\n");
    out.push_str("  }\n");
    out.push_str("};\n");
    out.push_str("memoTab.addEventListener('focus', function() {\n");
    out.push_str("  memoTab.addEventListener('keydown', tabInsert);\n");
    out.push_str("});\n");
    out.push_str("memoTab.addEventListener('blur', function() {\n");
    out.push_str("  memoTab.removeEventListener('keydown', tabInsert);\n");
    out.push_str("});\n");
    out.push_str("memoTab.addEventListener('keydown', function(e) {\n");
    out.push_str("  let endBracket = false;\n");
    out.push_str("  if (e.key === '(') {\n");
    out.push_str("    endBracket = ')';\n");
    out.push_str("  } else if (e.key === '{') {\n");
    out.push_str("    endBracket = '}';\n");
    out.push_str("  } else if (e.key === '[') {\n");
    out.push_str("    endBracket = ']';\n");
    out.push_str("  } else if (e.key === '\"') {\n");
    out.push_str("    endBracket = '\"';\n");
    out.push_str("  } else if (e.key === \"'\") {\n");
    out.push_str("    endBracket = \"'\";\n");
    out.push_str("  }\n");
    out.push_str("  const pos = this.selectionEnd;\n");
    out.push_str("  const textBefore = this.value.substring(0, pos);\n");
    out.push_str("  const textAfter = this.value.substring(pos, this.value.length);\n");
    out.push_str("  if (endBracket !== false) {\n");
    out.push_str("    e.preventDefault();\n");
    out.push_str("    this.value = textBefore + e.key + endBracket + textAfter;\n");
    out.push_str("    this.selectionStart = pos + 1;\n");
    out.push_str("    this.selectionEnd = pos + 1;\n");
    out.push_str("  }\n");
    out.push_str("  if ((textBefore.endsWith('(') && textAfter.startsWith(')') && e.key === ')') || (textBefore.endsWith('[') && textAfter.startsWith(']') && e.key === ']') || (textBefore.endsWith('{') && textAfter.startsWith('}') && e.key === '}')) {\n");
    out.push_str("    e.preventDefault();\n");
    out.push_str("    this.selectionStart = pos + 1;\n");
    out.push_str("    this.selectionEnd = pos + 1;\n");
    out.push_str("  }\n");
    out.push_str("  if ((textBefore.endsWith('\"') && textAfter.startsWith('\"') && e.key === '\"') || (textBefore.endsWith(\"'\") && textAfter.startsWith(\"'\") && e.key === \"'\")) {\n");
    out.push_str("    e.preventDefault();\n");
    out.push_str("    const cursorPosition = this.selectionStart;\n");
    out.push_str("    const text = this.value;\n");
    out.push_str("    const newText = text.substring(0, cursorPosition) + text.substring(cursorPosition + 1);\n");
    out.push_str("    this.value = newText;\n");
    out.push_str("    this.selectionStart = cursorPosition;\n");
    out.push_str("    this.selectionEnd = cursorPosition;\n");
    out.push_str("  }\n");
    out.push_str("  localStorage.setItem('memo', this.value);\n");
    out.push_str("});\n");
    out.push_str("function resizeMemo() {\n");
    out.push_str("  const distanceFromLeft = window.innerWidth - memoShell.offsetWidth;\n");
    out.push_str("  if (distanceFromLeft < 480) {\n");
    out.push_str("    memoShell.style.left = '470px';\n");
    out.push_str("    memoShell.style.width = `${window.innerWidth - MIN_MEMO_LEFT - 10}px`;\n");
    out.push_str("  } else {\n");
    out.push_str("    memoShell.style.left = 'auto';\n");
    out.push_str("  }\n");
    out.push_str("}\n");
    out.push_str("memoResizeHandle.addEventListener('pointerdown', function(event) {\n");
    out.push_str("  event.preventDefault();\n");
    out.push_str("  memoResizeHandle.setPointerCapture(event.pointerId);\n");
    out.push_str("  const resizeWithPointer = function(moveEvent) {\n");
    out.push_str(
        "    const maxWidth = Math.min(window.innerWidth - 10, Math.max(MIN_MEMO_WIDTH, (window.innerWidth - MIN_MEMO_LEFT - 10) * MEMO_MAX_WIDTH_MULTIPLIER));\n",
    );
    out.push_str("    const nextWidth = Math.max(MIN_MEMO_WIDTH, Math.min(maxWidth, window.innerWidth - moveEvent.clientX - 10));\n");
    out.push_str("    memoShell.style.width = `${nextWidth}px`;\n");
    out.push_str("    resizeMemo();\n");
    out.push_str("  };\n");
    out.push_str("  const stopResize = function() {\n");
    out.push_str("    memoResizeHandle.removeEventListener('pointermove', resizeWithPointer);\n");
    out.push_str("    memoResizeHandle.removeEventListener('pointerup', stopResize);\n");
    out.push_str("    memoResizeHandle.removeEventListener('pointercancel', stopResize);\n");
    out.push_str("  };\n");
    out.push_str("  memoResizeHandle.addEventListener('pointermove', resizeWithPointer);\n");
    out.push_str("  memoResizeHandle.addEventListener('pointerup', stopResize);\n");
    out.push_str("  memoResizeHandle.addEventListener('pointercancel', stopResize);\n");
    out.push_str("});\n");
    out.push_str("window.onresize = resizeMemo;\n");
    out.push_str("function clipping(copyText) {\n");
    out.push_str("  navigator.clipboard.writeText(copyText);\n");
    out.push_str("}\n");
    out.push_str("document.body.onkeydown = function(d){\n");
    out.push_str("  if (document.activeElement.id === 'memo') {\n");
    out.push_str("    return;\n");
    out.push_str("  }\n");
    out.push_str(shortcuts);
    out.push_str("};\n");
}

fn shortcut_condition(shortcut: Shortcut) -> Option<&'static str> {
    match shortcut {
        Shortcut::None => None,
        Shortcut::Key('A') => Some("d.keyCode == 65"),
        Shortcut::Key('B') => Some("d.keyCode == 66"),
        Shortcut::Key('C') => Some("d.keyCode == 67"),
        Shortcut::Key('D') => Some("d.keyCode == 68"),
        Shortcut::Key('E') => Some("d.keyCode == 69"),
        Shortcut::Key('F') => Some("d.keyCode == 70"),
        Shortcut::Key('G') => Some("d.keyCode == 71"),
        Shortcut::Key('H') => Some("d.keyCode == 72"),
        Shortcut::Key('I') => Some("d.keyCode == 73"),
        Shortcut::Key('J') => Some("d.keyCode == 74"),
        Shortcut::Key('K') => Some("d.keyCode == 75"),
        Shortcut::Key('L') => Some("d.keyCode == 76"),
        Shortcut::Key('M') => Some("d.keyCode == 77"),
        Shortcut::Key('N') => Some("d.keyCode == 78"),
        Shortcut::Key('O') => Some("d.keyCode == 79"),
        Shortcut::Key('P') => Some("d.keyCode == 80"),
        Shortcut::Key('Q') => Some("d.keyCode == 81"),
        Shortcut::Key('R') => Some("d.keyCode == 82"),
        Shortcut::Key('S') => Some("d.keyCode == 83"),
        Shortcut::Key('T') => Some("d.keyCode == 84"),
        Shortcut::Key('U') => Some("d.keyCode == 85"),
        Shortcut::Key('V') => Some("d.keyCode == 86"),
        Shortcut::Key('W') => Some("d.keyCode == 87"),
        Shortcut::Key('X') => Some("d.keyCode == 88"),
        Shortcut::Key('Y') => Some("d.keyCode == 89"),
        Shortcut::Key('Z') => Some("d.keyCode == 90"),
        Shortcut::Key(_) => None,
        Shortcut::Alt => Some("d.altKey"),
        Shortcut::ShiftSpace => Some("d.keyCode == 32 && d.shiftKey"),
    }
}

fn push_link_shortcut(shortcuts: &mut String, shortcut: Shortcut, url: &str) {
    let Some(condition) = shortcut_condition(shortcut) else {
        return;
    };
    shortcuts.push_str(LINK_SHORTCUT_MARKER);
    shortcuts.push('\n');
    shortcuts.push_str(&format!("  if ({condition}){{\n"));
    shortcuts.push_str(&format!(
        "    window.open('{}','_blank','noopener noreferrer');\n",
        js_single_quoted_string_escape(url)
    ));
    shortcuts.push_str("  }\n");
}

fn push_multi_link_shortcut(shortcuts: &mut String, shortcut: Shortcut, urls: &str) {
    let Some(condition) = shortcut_condition(shortcut) else {
        return;
    };
    let urls: Vec<&str> = urls
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .collect();
    if urls.is_empty() {
        return;
    }

    shortcuts.push_str(MULTI_LINK_SHORTCUT_MARKER);
    shortcuts.push('\n');
    shortcuts.push_str(&format!("  if ({condition}){{\n"));
    for url in urls {
        shortcuts.push_str(&format!(
            "    window.open('{}','_blank','noopener noreferrer');\n",
            js_single_quoted_string_escape(url)
        ));
    }
    shortcuts.push_str("  }\n");
}

fn html_unescape(value: &str) -> String {
    value
        .replace("&quot;", "\"")
        .replace("&#39;", "'")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&amp;", "&")
}

fn write_document_header(out: &mut String) {
    out.push_str(DOCTYPE_LINE);
    out.push('\n');
    out.push_str(HTML_OPEN);
    out.push('\n');
    out.push_str(GENERATED_MARKER);
    out.push('\n');
    out.push_str(
        r#"<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rapid</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+1+Code:wght@600&family=M+PLUS+Rounded+1c&family=Monomaniac+One&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet">
    <style>
      :root{
        --text-color-normal: black;
        --background-color-normal: white;
        --text-color-button: black;
        --background-color-button: #F0F0F0;
        --text-color-textarea: black;
        --background-color-textarea: white;
      }
      .dark-theme{
        --text-color-normal: #9CDCFE;
        --background-color-normal: black;
        --text-color-button: #5ED9C0;
        --background-color-button: #404040;
        --text-color-textarea: #5ED9C0;
        --background-color-textarea: black;
      }
      body{
        color: var(--text-color-normal);
        background-color: var(--background-color-normal);
        padding: 0 34rem 2rem 0;
      }
      h1{
        font-family: "Monomaniac One", sans-serif;
        font-weight: 400;
        font-style: normal;
      }
      details{
        display: inline-block;
      }
      .detail-content{
        position: relative;
        padding-left: 10px;
        overflow: hidden;
      }
      .detail-content::before{
        content: '';
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        border-left: 2px solid gray;
      }
      .dark-theme .detail-content::before{
        border-left: 2px solid #9C9CAE;
      }
      summary{
        font-size: 24px;
        font-family: "M PLUS 1 Code", monospace;
        font-optical-sizing: auto;
        font-weight: 600;
        font-style: normal;
      }
      a{
        display: inline-block;
        position: relative;
        overflow: hidden;
        text-decoration: none;
        vertical-align: middle;
      }
      a:after{
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 1px;
        background-color: black;
        transform: translate(-100%, 0);
        transition: transform cubic-bezier(0.215,0.61,0.355,1) 0.4s;
        content: "";
      }
      .dark-theme a:after{
        background-color: white;
      }
      a:hover:after{
        transform: translate(0,0)
      }
      a:link{color: blue;}
      a:visited{color: purple;}
      .dark-theme a:link{color: cyan;}
      .dark-theme a:visited{color: #6EE9D0;}
      button{
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border: 2px solid transparent;
        border-radius: 100px;
        padding: 4px 8px;
        margin: 1px;
        color: var(--text-color-button);
        background-color: var(--background-color-button);
        transition: border-color 0.3s ease, color 0.3s ease;
        cursor: pointer;
      }
      button:hover {
        background-color: #444444;
        color: white;
      }
      button.active {
        background-color: white;
        border-color: #444444;
        color: #444444;
      }
      .dark-theme button:hover {
        background-color: #222222;
        border-color: var(--text-color-button);
        color: #AEFFFF;
      }
      .dark-theme button.active {
        background-color: #DEFFFF;
        border-color: var(--text-color-button);
        color: #222222;
      }
      #memo-shell{
        right: 10px;
        position: fixed;
        height: calc(100vh - 20px);
        top: 10px;
        width: min(32rem, 42vw);
        min-width: 18rem;
        max-width: calc((100vw - 470px) * 1.25);
        box-sizing: border-box;
      }
      #memo{
        width: 100%;
        right: 0;
        position: absolute;
        height: 100%;
        top: 0;
        left: 0;
        box-sizing: border-box;
        display: block;
        color: var(--text-color-textarea);
        background-color: var(--background-color-textarea);
        resize: none;
      }
      #memo-resize-handle{
        position: absolute;
        left: -10px;
        bottom: 0;
        width: 20px;
        height: 20px;
        padding: 0;
        margin: 0;
        border-radius: 8px 8px 0 8px;
        border: 1px solid rgba(120, 120, 120, 0.75);
        background:
          linear-gradient(135deg, transparent 48%, rgba(120, 120, 120, 0.9) 48%, rgba(120, 120, 120, 0.9) 54%, transparent 54%),
          linear-gradient(135deg, transparent 66%, rgba(120, 120, 120, 0.9) 66%, rgba(120, 120, 120, 0.9) 72%, transparent 72%),
          var(--background-color-button);
        cursor: ew-resize;
      }
      #memo-resize-handle:hover {
        background:
          linear-gradient(135deg, transparent 48%, rgba(255, 255, 255, 0.95) 48%, rgba(255, 255, 255, 0.95) 54%, transparent 54%),
          linear-gradient(135deg, transparent 66%, rgba(255, 255, 255, 0.95) 66%, rgba(255, 255, 255, 0.95) 72%, transparent 72%),
          #444444;
      }
      .dark-theme #memo-resize-handle{
        border-color: rgba(94, 217, 192, 0.85);
        background:
          linear-gradient(135deg, transparent 48%, rgba(94, 217, 192, 0.95) 48%, rgba(94, 217, 192, 0.95) 54%, transparent 54%),
          linear-gradient(135deg, transparent 66%, rgba(94, 217, 192, 0.95) 66%, rgba(94, 217, 192, 0.95) 72%, transparent 72%),
          #202020;
      }
      .dark-theme #memo-resize-handle:hover {
        background:
          linear-gradient(135deg, transparent 48%, rgba(174, 255, 255, 1) 48%, rgba(174, 255, 255, 1) 54%, transparent 54%),
          linear-gradient(135deg, transparent 66%, rgba(174, 255, 255, 1) 66%, rgba(174, 255, 255, 1) 72%, transparent 72%),
          #161616;
      }
      .copy-message{
        color: green;
        display: none;
      }
      .dark-theme .copy-message{
        color: #AEFFFF;
        display: none;
      }
      .key-viewer{
        color: deepskyblue;
        display: inline-block;
        vertical-align: middle;
      }
      .key-viewer-fullopen{
        color: red;
      }
      .dark-theme .key-viewer-fullopen{
        color: #E6DF99;
      }
      .page-actions{
        display: flex;
        flex-wrap: wrap;
        gap: 0.35rem;
        margin-bottom: 1rem;
      }
      footer{
        color: gray;
        font-size: 12px;
      }
    </style>
</head>
<body>
<div id="memo-shell">
<textarea id="memo" placeholder="[メモ欄]"></textarea>
<button id="memo-resize-handle" aria-label="メモ欄の幅を変更" title="メモ欄の幅を変更"></button>
</div>
<h1>Rapid</h1>
"#,
    );
}

fn write_document_controls(out: &mut String) {
    out.push_str(
        r#"<div class="page-actions">
<button id="theme">ダークモード</button>
</div>
"#,
    );
}

fn write_document_footer(out: &mut String) {
    out.push_str(
        r#"<footer>
<br><br>Rapid URL Collection<br>
Author: Mel's Rough Sketch<br>
License: Apache 2.0<br>
</footer>
</body>
"#,
    );
    out.push_str(HTML_CLOSE);
    out.push('\n');
}

#[derive(Debug, PartialEq, Eq)]
enum ParsedLine<'a> {
    Ignored,
    OpenSection,
    SectionTitle(&'a str),
    TextItem(&'a str),
    LinkItem {
        text: String,
        url: String,
        shortcut: Shortcut,
    },
    MultiLinkItem {
        text: String,
        urls: String,
        shortcut: Shortcut,
    },
    CopyButtonItem {
        text: String,
        body: String,
    },
    ManualLineBreak,
    CloseSection,
}

fn parse_line(line: &str) -> Result<ParsedLine<'_>, HtmlError> {
    if is_ignored_line(line) {
        return Ok(ParsedLine::Ignored);
    }
    if is_details_open(line) {
        return Ok(ParsedLine::OpenSection);
    }
    if let Some(value) = strip_wrapped(line, SUMMARY_OPEN, SUMMARY_CLOSE) {
        return Ok(ParsedLine::SectionTitle(value));
    }
    if let Some(value) = strip_wrapped(line, TEXT_ITEM_OPEN, TEXT_ITEM_CLOSE) {
        return Ok(ParsedLine::TextItem(value));
    }
    if let Some(parsed) = parse_link_line(line) {
        return Ok(parsed);
    }
    if let Some(parsed) = parse_copy_button_line(line) {
        return Ok(parsed);
    }
    if let Some(parsed) = parse_multi_link_line(line) {
        return Ok(parsed);
    }
    if line == MANUAL_LINE_BREAK {
        return Ok(ParsedLine::ManualLineBreak);
    }
    if line == DETAILS_CLOSE {
        return Ok(ParsedLine::CloseSection);
    }

    Ok(ParsedLine::Ignored)
}

fn is_ignored_line(line: &str) -> bool {
    line.is_empty()
        || matches!(
            line,
            DOCTYPE_LINE | HTML_OPEN | HTML_CLOSE | GENERATED_MARKER | SCRIPT_OPEN | SCRIPT_CLOSE
        )
}

fn is_details_open(line: &str) -> bool {
    line == DETAILS_OPEN || line.starts_with("<details ")
}

fn strip_wrapped<'a>(line: &'a str, prefix: &str, suffix: &str) -> Option<&'a str> {
    line.strip_prefix(prefix)?.strip_suffix(suffix)
}

fn parse_link_line(line: &str) -> Option<ParsedLine<'_>> {
    let (shortcut, link_html) = if let Some(rest) = line.strip_prefix(KEY_VIEWER_OPEN) {
        let key_end = rest.find(KEY_VIEWER_CLOSE)?;
        let shortcut = parse_shortcut_label(&rest[..key_end])?;
        (shortcut, &rest[key_end + KEY_VIEWER_CLOSE.len()..])
    } else {
        (Shortcut::None, line)
    };

    let url = link_html.strip_prefix(LINK_OPEN)?;
    let url_end = url.find('"')?;
    let text_start = link_html.find('>')? + 1;
    let text_end = link_html.rfind(LINK_CLOSE)?;
    Some(ParsedLine::LinkItem {
        text: html_unescape(&link_html[text_start..text_end]),
        url: html_unescape(&url[..url_end]),
        shortcut,
    })
}

fn parse_multi_link_line(line: &str) -> Option<ParsedLine<'_>> {
    if let Some(rest) = line.strip_prefix(KEY_VIEWER_FULLOPEN_NONE_OPEN) {
        let (encoded_urls, rest) = rest.split_once(KEY_VIEWER_FULLOPEN_NONE_MID)?;
        let text = rest.strip_suffix("<br>")?;
        return Some(ParsedLine::MultiLinkItem {
            text: html_unescape(text),
            urls: js_single_quoted_string_unescape(&html_unescape(encoded_urls)),
            shortcut: Shortcut::None,
        });
    }

    let rest = line.strip_prefix(KEY_VIEWER_FULLOPEN_OPEN)?;
    let key_end = rest.find(KEY_VIEWER_CLOSE)?;
    let shortcut = parse_shortcut_label(&rest[..key_end])?;
    let text = rest[key_end + KEY_VIEWER_CLOSE.len()..].strip_suffix("<br>")?;
    Some(ParsedLine::MultiLinkItem {
        text: html_unescape(text),
        urls: String::new(),
        shortcut,
    })
}

fn parse_copy_button_line(line: &str) -> Option<ParsedLine<'_>> {
    let rest = line.strip_prefix(COPY_BUTTON_OPEN)?;
    let onclick_end = rest.find("\">")?;
    let onclick = html_unescape(&rest[..onclick_end]);
    let text = rest[onclick_end + 2..].strip_suffix(COPY_BUTTON_CLOSE)?;
    let body = parse_copy_body(&onclick)?;
    Some(ParsedLine::CopyButtonItem {
        text: html_unescape(text),
        body,
    })
}

fn parse_copy_body(onclick: &str) -> Option<String> {
    let body = onclick.strip_prefix("clipping('")?.strip_suffix("')")?;
    Some(js_single_quoted_string_unescape(body))
}

fn js_single_quoted_string_unescape(value: &str) -> String {
    let mut out = String::new();
    let mut chars = value.chars();
    while let Some(ch) = chars.next() {
        if ch != '\\' {
            out.push(ch);
            continue;
        }

        match chars.next() {
            Some('n') => out.push('\n'),
            Some('r') => out.push('\r'),
            Some('\'') => out.push('\''),
            Some('"') => out.push('"'),
            Some('\\') => out.push('\\'),
            Some(other) => {
                out.push('\\');
                out.push(other);
            }
            None => out.push('\\'),
        }
    }
    out
}

fn multi_link_urls_attr_escape(value: &str) -> String {
    html_attr_escape(&js_single_quoted_string_escape(value))
}

fn parse_shortcut_label(label: &str) -> Option<Shortcut> {
    match label {
        "Alt" => Some(Shortcut::Alt),
        "Shift + Space" | "Shift+Space" => Some(Shortcut::ShiftSpace),
        "Alt+A" => Shortcut::key('A'),
        "Alt+S" => Shortcut::key('S'),
        "Alt+D" => Shortcut::key('D'),
        other if other.len() == 1 => Shortcut::key(other.chars().next()?),
        _ => None,
    }
}

#[derive(Debug, Clone)]
enum ShortcutBlockKind {
    Unknown,
    Link,
    MultiLink,
}

#[derive(Debug, Clone)]
struct ShortcutUrls {
    kind: ShortcutBlockKind,
    shortcut: Shortcut,
    urls: Vec<String>,
}

fn parse_script_shortcut_blocks(lines: &[String]) -> Vec<ShortcutUrls> {
    let mut blocks = Vec::new();
    let mut current: Option<ShortcutUrls> = None;
    let mut pending_kind = ShortcutBlockKind::Unknown;

    for line in lines {
        if let Some(kind) = parse_script_block_kind(line) {
            pending_kind = kind;
            continue;
        }

        if let Some(shortcut) = parse_script_shortcut(line) {
            finish_shortcut_block(&mut current, &mut blocks);
            current = Some(ShortcutUrls {
                kind: pending_kind.clone(),
                shortcut,
                urls: Vec::new(),
            });
            pending_kind = ShortcutBlockKind::Unknown;
            continue;
        }

        if let Some(block) = current.as_mut() {
            if let Some(url) = parse_window_open_literal_url(line) {
                block.urls.push(url);
                continue;
            }

            if line.starts_with('}') {
                finish_shortcut_block(&mut current, &mut blocks);
            }
        }
    }

    finish_shortcut_block(&mut current, &mut blocks);

    blocks
}

fn finish_shortcut_block(current: &mut Option<ShortcutUrls>, blocks: &mut Vec<ShortcutUrls>) {
    if let Some(block) = current.take()
        && !block.urls.is_empty()
    {
        blocks.push(block);
    }
}

fn parse_script_block_kind(line: &str) -> Option<ShortcutBlockKind> {
    match line {
        LINK_SHORTCUT_MARKER => Some(ShortcutBlockKind::Link),
        MULTI_LINK_SHORTCUT_MARKER => Some(ShortcutBlockKind::MultiLink),
        _ => None,
    }
}

fn parse_script_shortcut(line: &str) -> Option<Shortcut> {
    if line.contains("shiftKey") && (line.contains("keyCode == 32") || line.contains("key === ' '"))
    {
        return Some(Shortcut::ShiftSpace);
    }

    if let Some(shortcut) = parse_script_letter_shortcut(line) {
        return Some(shortcut);
    }

    if line.contains("altKey") {
        return Some(Shortcut::Alt);
    }

    None
}

fn parse_script_letter_shortcut(line: &str) -> Option<Shortcut> {
    for code in b'A'..=b'Z' {
        let uppercase = char::from(code);
        let lowercase = uppercase.to_ascii_lowercase();
        let key_code = format!("keyCode == {code}");
        let single_quoted = format!("key === '{lowercase}'");
        let double_quoted = format!("key === \"{lowercase}\"");
        let uppercase_single_quoted = format!("key === '{uppercase}'");
        let uppercase_double_quoted = format!("key === \"{uppercase}\"");

        if line.contains(&key_code)
            || line.contains(&single_quoted)
            || line.contains(&double_quoted)
            || line.contains(&uppercase_single_quoted)
            || line.contains(&uppercase_double_quoted)
        {
            return Shortcut::key(uppercase);
        }
    }

    None
}

fn parse_window_open_literal_url(line: &str) -> Option<String> {
    let (_, rest) = line.split_once("window.open('")?;
    let url = rest.split_once("','")?.0;
    Some(js_single_quoted_string_unescape(&html_unescape(url)))
}

fn restore_multi_link_urls(sections: &mut [Section], shortcut_blocks: &[ShortcutUrls]) {
    let mut remaining = shortcut_blocks.to_vec();
    restore_multi_link_urls_in_sections(sections, &mut remaining);
}

fn restore_multi_link_urls_in_sections(
    sections: &mut [Section],
    remaining: &mut Vec<ShortcutUrls>,
) {
    for section in sections {
        for item in &mut section.items {
            if let ItemKind::MultiLink { urls, shortcut, .. } = &mut item.kind
                && let Some(index) = remaining.iter().position(|block| {
                    block.shortcut == *shortcut && !matches!(block.kind, ShortcutBlockKind::Link)
                })
            {
                let block = remaining.remove(index);
                *urls = block.urls.join("\n");
            }
        }
        restore_multi_link_urls_in_sections(&mut section.sections, remaining);
    }
}

fn current_section_mut<'a>(
    stack: &'a mut [Section],
    message: &'static str,
) -> Result<&'a mut Section, HtmlError> {
    stack.last_mut().ok_or_else(|| invalid_structure(message))
}

fn close_section(
    stack: &mut Vec<Section>,
    root_sections: &mut Vec<Section>,
) -> Result<(), HtmlError> {
    let section = stack
        .pop()
        .ok_or_else(|| invalid_structure("unmatched </details>"))?;
    if let Some(parent) = stack.last_mut() {
        parent.sections.push(section);
    } else {
        root_sections.push(section);
    }
    Ok(())
}

fn invalid_structure(message: impl Into<String>) -> HtmlError {
    HtmlError::InvalidStructure(message.into())
}

fn parsed_line_break_item() -> Item {
    Item::line_break()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Document, Item, ItemKind, Section, Shortcut};

    fn root_section(items: Vec<Item>) -> Section {
        Section {
            id: 1,
            title: "Root".into(),
            sections: vec![],
            items,
        }
    }

    fn document_with_items(items: Vec<Item>) -> Document {
        Document {
            sections: vec![root_section(items)],
        }
    }

    fn link_item(text: &str, url: &str, shortcut: Shortcut) -> Item {
        Item {
            id: 2,
            kind: ItemKind::Link {
                text: text.into(),
                url: url.into(),
                shortcut,
            },
        }
    }

    fn multi_link_item(text: &str, urls: &str, shortcut: Shortcut) -> Item {
        Item {
            id: 2,
            kind: ItemKind::MultiLink {
                text: text.into(),
                urls: urls.into(),
                shortcut,
            },
        }
    }

    fn copy_button_item(text: &str, body: &str) -> Item {
        Item {
            id: 2,
            kind: ItemKind::CopyButton {
                text: text.into(),
                body: body.into(),
            },
        }
    }

    fn generated_html(body: &str, script_body: &str) -> String {
        format!(
            "<!DOCTYPE html>\n<html>\n<!--THIS FILE IS GENERATED BY URLS EDITOR-->\n{body}\n<script>\n{script_body}\n</script>\n</html>\n"
        )
    }

    #[test]
    fn generate_single_link_html() {
        let document =
            document_with_items(vec![link_item("Open", "https://example.com", Shortcut::None)]);

        let html = render_document(&document);
        assert!(html.contains("<html lang=\"ja\">"));
        assert!(html.contains("<title>Rapid</title>"));
        assert!(html.contains("<h1>Rapid</h1>"));
        assert!(html.contains("<summary class=\"summary\">Root</summary>"));
        assert!(html.contains("https://example.com"));
    }

    #[test]
    fn generated_document_includes_required_head_assets_without_search_bar() {
        let document = Document {
            sections: vec![Section::new("Root")],
        };

        let html = render_document(&document);
        assert!(html.contains("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">"));
        assert!(
            html.contains(
                "<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>"
            )
        );
        assert!(html.contains("family=M+PLUS+1+Code"));
        assert!(html.contains("font-awesome/4.7.0/css/font-awesome.min.css"));
        assert!(html.contains("font-awesome/6.5.2/css/all.min.css"));
        assert!(!html.contains("search_container"));
        assert!(!html.contains("searchBox"));
        assert!(!html.contains("Search on Google"));
    }

    #[test]
    fn generated_document_includes_memo_theme_and_footer_shell() {
        let document = Document {
            sections: vec![Section::new("Root")],
        };

        let html = render_document(&document);
        assert!(html.contains("<div id=\"memo-shell\">"));
        assert!(html.contains("<textarea id=\"memo\" placeholder=\"[メモ欄]\"></textarea>"));
        assert!(html.contains("<button id=\"memo-resize-handle\" aria-label=\"メモ欄の幅を変更\" title=\"メモ欄の幅を変更\"></button>"));
        assert!(html.contains("memoResizeHandle.addEventListener('pointerdown'"));
        assert!(html.contains("const INITIAL_MEMO_WIDTH_RATIO = 0.5;"));
        assert!(html.contains("const MEMO_MAX_WIDTH_MULTIPLIER = 1.25;"));
        assert!(html.contains("memoShell.style.width = `${Math.round(window.innerWidth * INITIAL_MEMO_WIDTH_RATIO)}px`;"));
        assert!(html.contains("max-width: calc((100vw - 470px) * 1.25);"));
        assert!(html.contains("const maxWidth = Math.min(window.innerWidth - 10, Math.max(MIN_MEMO_WIDTH, (window.innerWidth - MIN_MEMO_LEFT - 10) * MEMO_MAX_WIDTH_MULTIPLIER));"));
        assert!(html.contains("<button id=\"theme\">ダークモード</button>"));
        assert!(!html.contains("toggleButton"));
        assert!(!html.contains("tabToSpace()"));
        assert!(!html.contains("spaceToTab()"));
        assert!(html.contains("Author: Mel's Rough Sketch"));
        assert!(html.contains("License: Apache 2.0"));
    }

    #[test]
    fn generate_keyed_link_includes_shortcut_script() {
        let document =
            document_with_items(vec![link_item("Open", "https://example.com", Shortcut::Key('A'))]);

        let html = render_document(&document);
        assert!(html.contains("<span class=\"key-viewer\">[A]</span>"));
        assert!(html.contains("function clipping(copyText) {"));
        assert!(html.contains("document.body.onkeydown = function(d){"));
        assert!(html.contains("if (d.keyCode == 65){"));
        assert!(
            html.contains("window.open('https://example.com','_blank','noopener noreferrer');")
        );
    }

    #[test]
    fn generated_document_round_trips_multi_link_urls() {
        let original = document_with_items(vec![multi_link_item(
            "Open related links",
            "https://a.example.com\nhttps://b.example.com",
            Shortcut::ShiftSpace,
        )]);

        let html = render_document(&original);
        assert!(html.contains("document.body.onkeydown = function(d){"));
        assert!(
            html.contains("window.open('https://a.example.com','_blank','noopener noreferrer');")
        );
        let parsed = parse_document(&html).unwrap();
        match &parsed.sections[0].items[0].kind {
            ItemKind::MultiLink {
                text,
                urls,
                shortcut,
            } => {
                assert_eq!(text, "Open related links");
                assert_eq!(urls, "https://a.example.com\nhttps://b.example.com");
                assert_eq!(*shortcut, Shortcut::ShiftSpace);
            }
            other => panic!("unexpected item: {other:?}"),
        }
    }

    #[test]
    fn generate_python_compatible_single_key_shortcut() {
        let document =
            document_with_items(vec![link_item("Open", "https://example.com", Shortcut::Key('A'))]);

        let html = render_document(&document);
        assert!(html.contains("<span class=\"key-viewer\">[A]</span>"));
        assert!(html.contains("if (d.keyCode == 65){"));
        assert!(!html.contains("[Alt+A]"));
    }

    #[test]
    fn generate_python_compatible_multi_link_alt_shortcut() {
        let document = document_with_items(vec![multi_link_item(
            "Open related links",
            "https://a.example.com\nhttps://b.example.com",
            Shortcut::Alt,
        )]);

        let html = render_document(&document);
        assert!(html.contains("<span class=\"key-viewer-fullopen\">[Alt]</span>"));
        assert!(html.contains("if (d.altKey){"));
    }

    #[test]
    fn generated_document_round_trips_keyed_single_link_and_single_url_multi_link() {
        let original = document_with_items(vec![
            link_item("Open", "https://example.com", Shortcut::Key('A')),
            Item {
                id: 3,
                kind: ItemKind::MultiLink {
                    text: "Open related".into(),
                    urls: "https://example.com".into(),
                    shortcut: Shortcut::Key('A'),
                },
            },
        ]);

        let html = render_document(&original);
        let parsed = parse_document(&html).unwrap();
        match &parsed.sections[0].items[1].kind {
            ItemKind::MultiLink {
                text,
                urls,
                shortcut,
            } => {
                assert_eq!(text, "Open related");
                assert_eq!(urls, "https://example.com");
                assert_eq!(*shortcut, Shortcut::Key('A'));
            }
            other => panic!("unexpected item: {other:?}"),
        }
    }

    #[test]
    fn generate_copy_button_escapes_newlines_and_quotes() {
        let document = document_with_items(vec![copy_button_item("Copy", "a'b\nc")]);

        let html = render_document(&document);
        assert!(html.contains("onclick=\"clipping(&#39;a\\&#39;b\\nc&#39;)\""));
        assert!(html.contains("function clipping(copyText) {"));
        assert!(html.contains("navigator.clipboard.writeText(copyText);"));
    }

    #[test]
    fn generated_document_round_trips_multi_link_without_shortcut() {
        let original = document_with_items(vec![multi_link_item(
            "Open related links",
            "https://a.example.com\nhttps://b.example.com",
            Shortcut::None,
        )]);

        let html = render_document(&original);
        assert!(html.contains(
            "<span class=\"key-viewer-fullopen\" data-shortcut=\"none\" data-urls=\"https://a.example.com\\nhttps://b.example.com\"></span>Open related links<br>"
        ));
        assert!(!html.contains("[Shift+Space]"));
        let parsed = parse_document(&html).unwrap();
        match &parsed.sections[0].items[0].kind {
            ItemKind::MultiLink {
                text,
                urls,
                shortcut,
            } => {
                assert_eq!(text, "Open related links");
                assert_eq!(urls, "https://a.example.com\nhttps://b.example.com");
                assert_eq!(*shortcut, Shortcut::None);
            }
            other => panic!("unexpected item: {other:?}"),
        }
    }

    #[test]
    fn generate_link_escapes_href_attribute_context() {
        let document = document_with_items(vec![link_item(
            "Open",
            "https://example.com/?q=\" onclick=\"alert(1)",
            Shortcut::None,
        )]);

        let html = render_document(&document);
        assert!(html.contains("href=\"https://example.com/?q=&quot; onclick=&quot;alert(1)\""));
    }

    #[test]
    fn generate_copy_button_escapes_html_attribute_and_js_string_contexts() {
        let document =
            document_with_items(vec![copy_button_item("Copy", "a\" onclick=\"alert(1)\nb")]);

        let html = render_document(&document);
        assert!(
            html.contains("onclick=\"clipping(&#39;a\\&quot; onclick=\\&quot;alert(1)\\nb&#39;)\"")
        );
    }

    #[test]
    fn parse_plain_link_item() {
        let html = generated_html(
            "<details open>\n<summary class=\"summary\">Root</summary>\n<a href=\"https://example.com\" target=\"_blank\" rel=\"noopener noreferrer\">Open</a><br>\n</details>",
            "",
        );

        let document = parse_document(&html).unwrap();
        match &document.sections[0].items[0].kind {
            ItemKind::Link {
                text,
                url,
                shortcut,
            } => {
                assert_eq!(text, "Open");
                assert_eq!(url, "https://example.com");
                assert_eq!(*shortcut, Shortcut::None);
            }
            other => panic!("unexpected item: {other:?}"),
        }
    }

    #[test]
    fn parse_keyed_link_item() {
        let html = generated_html(
            "<details open>\n<summary class=\"summary\">Root</summary>\n<span class=\"key-viewer\">[A]</span><a href=\"https://example.com\" target=\"_blank\" rel=\"noopener noreferrer\">Open</a><br>\n</details>",
            "",
        );

        let document = parse_document(&html).unwrap();
        match &document.sections[0].items[0].kind {
            ItemKind::Link {
                text,
                url,
                shortcut,
            } => {
                assert_eq!(text, "Open");
                assert_eq!(url, "https://example.com");
                assert_eq!(*shortcut, Shortcut::Key('A'));
            }
            other => panic!("unexpected item: {other:?}"),
        }
    }

    #[test]
    fn parse_copy_button_item() {
        let html = generated_html(
            "<details open>\n<summary class=\"summary\">Root</summary>\n<button onclick=\"clipping('hello\\nworld')\">Copy <i class=\"fa-regular fa-copy\"></i></button><br>\n</details>",
            "",
        );

        let document = parse_document(&html).unwrap();
        match &document.sections[0].items[0].kind {
            ItemKind::CopyButton { text, body } => {
                assert_eq!(text, "Copy");
                assert_eq!(body, "hello\nworld");
            }
            other => panic!("unexpected item: {other:?}"),
        }
    }

    #[test]
    fn parse_multi_link_item() {
        let html = generated_html(
            "<details open>\n<summary class=\"summary\">Root</summary>\n<span class=\"key-viewer-fullopen\">[Shift + Space]</span>Open related links<br>\n</details>",
            "",
        );

        let document = parse_document(&html).unwrap();
        match &document.sections[0].items[0].kind {
            ItemKind::MultiLink {
                text,
                urls,
                shortcut,
            } => {
                assert_eq!(text, "Open related links");
                assert_eq!(urls, "");
                assert_eq!(*shortcut, Shortcut::ShiftSpace);
            }
            other => panic!("unexpected item: {other:?}"),
        }
    }

    #[test]
    fn parse_python_alt_multi_link_urls_from_script_body() {
        let html = generated_html(
            "<details open>\n<summary class=\"summary\">Root</summary>\n<div class=\"detail-content\">\n<span class=\"key-viewer-fullopen\">[Alt]</span>Open related links<br>\n</div>\n</details>",
            "if (d.altKey) {\n  window.open('https://a.example.com','_blank','noopener noreferrer');\n  window.open('https://b.example.com','_blank','noopener noreferrer');\n}",
        );

        let document = parse_document(&html).unwrap();
        match &document.sections[0].items[0].kind {
            ItemKind::MultiLink {
                text,
                urls,
                shortcut,
            } => {
                assert_eq!(text, "Open related links");
                assert_eq!(urls, "https://a.example.com\nhttps://b.example.com");
                assert_eq!(*shortcut, Shortcut::Alt);
            }
            other => panic!("unexpected item: {other:?}"),
        }
    }

    #[test]
    fn parse_document_ignores_non_empty_script_body() {
        let html = generated_html(
            "<details open>\n<summary class=\"summary\">Root</summary>\n<span>hello</span><br>\n</details>",
            "function clipping(copyText) {\n  navigator.clipboard.writeText(copyText);\n}",
        );

        let document = parse_document(&html).unwrap();
        assert_eq!(document.sections.len(), 1);
        assert_eq!(document.sections[0].items.len(), 1);
    }

    #[test]
    fn parse_multi_link_urls_from_script_body() {
        let html = generated_html(
            "<details open>\n<summary class=\"summary\">Root</summary>\n<span class=\"key-viewer-fullopen\">[Shift + Space]</span>Open related links<br>\n</details>",
            "if (event.shiftKey && event.key === ' ') {\n  window.open('https://a.example.com','_blank','noopener noreferrer');\n  window.open('https://b.example.com','_blank','noopener noreferrer');\n}",
        );

        let document = parse_document(&html).unwrap();
        match &document.sections[0].items[0].kind {
            ItemKind::MultiLink {
                text,
                urls,
                shortcut,
            } => {
                assert_eq!(text, "Open related links");
                assert_eq!(urls, "https://a.example.com\nhttps://b.example.com");
                assert_eq!(*shortcut, Shortcut::ShiftSpace);
            }
            other => panic!("unexpected item: {other:?}"),
        }
    }


    #[test]
    fn parse_document_preserves_section_title_without_special_cases() {
        let html = generated_html(
            "<details open>\n<summary class=\"summary\">tool</summary>\n</details>",
            "",
        );

        let document = parse_document(&html).unwrap();
        assert_eq!(document.sections[0].title, "tool");
    }

    #[test]
    fn parse_generated_single_section_document() {
        let html = generated_html(
            "<details open>\n<summary class=\"summary\">Root</summary>\n<span>hello</span><br>\n</details>",
            "",
        );

        let document = parse_document(&html).unwrap();
        assert_eq!(document.sections.len(), 1);
        assert_eq!(document.sections[0].title, "Root");
        assert_eq!(document.sections[0].items.len(), 1);
    }

    #[test]
    fn generated_document_round_trips_text_items() {
        let original = document_with_items(vec![Item::text("hello")]);

        let html = render_document(&original);
        let parsed = parse_document(&html).unwrap();
        assert_eq!(parsed.sections[0].title, "Root");
        assert_eq!(parsed.sections[0].items.len(), 1);
    }

    #[test]
    fn parse_document_rejects_summary_outside_section() {
        let html =
            generated_html("<summary class=\"summary\">Root</summary>", "");

        let error = parse_document(&html).unwrap_err();
        assert_eq!(
            error.to_string(),
            "invalid HTML structure: summary outside section"
        );
    }

    #[test]
    fn parse_document_rejects_text_item_outside_section() {
        let html = generated_html("<span>hello</span><br>", "");

        let error = parse_document(&html).unwrap_err();
        assert_eq!(
            error.to_string(),
            "invalid HTML structure: text item outside section"
        );
    }

    #[test]
    fn parse_document_rejects_manual_line_break_outside_section() {
        let html = generated_html("<!--MANUAL LINE BREAK-->", "");

        let error = parse_document(&html).unwrap_err();
        assert_eq!(
            error.to_string(),
            "invalid HTML structure: manual line break outside section"
        );
    }

    #[test]
    fn parse_document_assigns_distinct_ids_to_loaded_non_text_items() {
        let html = "\
<!DOCTYPE html>
<html>
<!--THIS FILE IS GENERATED BY URLS EDITOR-->
<details open>
<summary class=\"summary\">Root</summary>
<span class=\"key-viewer\">[Alt+A]</span><a href=\"https://example.com\" target=\"_blank\" rel=\"noopener noreferrer\">Open</a><br>
<span class=\"key-viewer-fullopen\">[Shift+Space]</span>Open related links<br>
<button onclick=\"clipping('hello')\">Copy <i class=\"fa-regular fa-copy\"></i></button><br>
<!--MANUAL LINE BREAK-->
</details>
<script>
</script>
</html>
";

        let document = parse_document(html).unwrap();
        let items = &document.sections[0].items;
        assert_eq!(items.len(), 4);

        let ids: std::collections::HashSet<u64> = items.iter().map(|item| item.id).collect();
        assert_eq!(ids.len(), items.len());
        assert!(!ids.contains(&0));
    }

    #[test]
    fn parse_nested_sections() {
        let html = "\
<!DOCTYPE html>
<html>
<!--THIS FILE IS GENERATED BY URLS EDITOR-->
<details open>
<summary class=\"summary\">Parent</summary>
<details open>
<summary class=\"summary\">Child</summary>
</details>
</details>
<script>
</script>
</html>
";

        let document = parse_document(html).unwrap();
        assert_eq!(document.sections[0].sections[0].title, "Child");
    }

    #[test]
    fn save_document_writes_generated_marker() {
        let temp_dir = std::env::temp_dir().join(format!("editor-rust-{}", std::process::id()));
        std::fs::create_dir_all(&temp_dir).unwrap();
        let path = temp_dir.join("Rapid.html");
        let document = Document::default_document();

        save_document_to_path(&document, &path).unwrap();

        let saved = std::fs::read_to_string(path).unwrap();
        assert!(saved.contains("<!--THIS FILE IS GENERATED BY URLS EDITOR-->"));
    }

    #[test]
    fn output_path_uses_rapid_html_name() {
        assert_eq!(
            rapid_path().file_name().and_then(|name| name.to_str()),
            Some("Rapid.html")
        );
    }
}
